### ISSUE TITLE
Module improvement suggestions

### ISSUE THREAD

**Issue by pi0** [inkline/nuxt-module-inkline#2]
Thanks for the nice module for Nuxt integration 💚 I have a few suggestions to improve module structure:

- Please consider migrating to use [module-builder](https://github.com/nuxt/module-builder) for properly building modules with the latest recommendations
- Please consider the following module starter (https://github.com/nuxt/starter/tree/module)
   - Runtime code like plugins should be in `src/runtime/`
   - Dependency of `@nuxt/kit` should be `"@nuxt/kit": "npm:@nuxt/kit-edge@latest"`
   - See new usage of new URL in `src/module.ts` for resolving paths

Also related note regarding Nuxt 3 documentation (https://inkline.io/docs/introduction/installation/nuxt)

- Please simplify "Nuxt.js 3" references to "Nuxt" (https://v3.nuxtjs.org/docs/advanced/modules#do-not-advertise-with-a-specific-nuxt-version)
- With Nuxt 3, it is preferred to put styles inside `app.vue` instead of creating `main.scss`

**Comment by alexgrozav** [comment]
Thank you so much for reviewing this, @pi0! I'll take care of the changes. 🙌
